# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hello-world}
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["kunto aji"]
  s.date = %q{2010-01-14}
  s.default_executable = %q{hello-world}
  s.description = %q{longer description of your gem}
  s.email = %q{aji_okay@yahoo.co.id}
  s.executables = ["hello-world"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/hello-world",
     "hello-world.gemspec",
     "lib/hello-world.rb",
     "test/helper.rb",
     "test/test_hello-world.rb"
  ]
  s.homepage = %q{http://github.com/kuntoaji/hello-world}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{one-line summary of your gem}
  s.test_files = [
    "test/test_hello-world.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

